### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by huylenguyen** [digiLab-ai/twinLab-client#11]
Currently, error messages are not being correctly propagated to the caller. For example, I am getting this error message if I forget to upload my dataset:

```
File [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py:355](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py:355), in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is not particularly helpful. Can we improve this so that the error is correctly propagated back to the user?

**Comment by huylenguyen** [comment]
This error is the same if the csv has `NaN` or missing input/output columns.

**Comment by alexander-mead** [comment]
This is better now, in that error messages generated by the `twinLab` library are automatically passed to the client, but it still needs some work so as not to deluge the client with information.

**Comment by alexander-mead** [comment]
Fixed!
