### ISSUE TITLE
Outputs of evaluation to also include confidence intervals

### ISSUE THREAD

**Issue by whornsby82** [digiLab-ai/twinLab-client#8]
Would it be possible to also output the confidence intervals for the the model outputs?

**Comment by alexander-mead** [comment]
Thanks for your question. When you call the `tl.sample_campaign` function, it should return two dataframes, the first is the mean value of the `twinLab` prediction, while the second dataframe should contain the corresponding errors. These are the Gaussian one-sigma confidence bounds.

For example, if you plot the lines `df_mean['y']-df_std['y']` and `df_mean['y']+df_std['y']` for some prediction `'y'`, these should encompass the ~68% confidence region.

Does that help?

**Comment by whornsby82** [comment]
Ah I've got it.  Yeh that's cool.  Ive been getting csv files with all the parameters including errors in them appended with '_upper' and '_lower', it would be good to replicate this.
